#!/usr/bin/env perl -w
#
# Ensure that all commit messages are prefixed with
# a ticket number, if appropriate.
#
# First, see if the current branch begins with something
# that looks like a Jira ticket (like ABC-1235).
# If the branch does start with a ticket,
# check to see if the message already begins with
# something that looks like a Jira ticket.
#
# If the message does not start with a ticket, then prepend
# the ticket number from the branch.
#
# This makes it easier for future us to see what ticket corresponds
# to each of the commits when looking through history.
#
# Examples:
# branch: "a new branch"
# msg:    "a message"
# result: "a message"
#
# branch: "ABC-123.a-new-branch
# msg:    "a message"
# result: "ABC-123 a message"
#
# branch: "ABC-123.a-new-branch
# msg:    "XYZ-789 a message"
# result: "XYZ-789 a message"
#

my $msgfile  = shift @ARGV;
my $branch   = `git symbolic-ref --short HEAD`;
my $isjira   = "^([A-Z]+-\\d+)";
my ($issue)  = ($branch =~ /$isjira/);

if ($issue) {
    local $/ = undef;
    my ($fh, $msg);

    open($fh, "+<", $msgfile);
    $msg  = <$fh>;

    unless ($msg =~ /$isjira/) {
        seek($fh, 0, 0);
        print $fh ($issue, " ", $msg);
    }
    $fh->close;
}
